run:
  tests: false
  timeout: 5m
  output:
    format: tab
  skip-dirs:
    - vendor
linters:
  enable-all: true
  disable:
  # need to try on
    - promlinter
    - wrapcheck
  # too much false positive
    - depguard
    - lll
    - wsl
    - tagliatelle
    - exhaustruct
    - nlreturn
    - varnamelen
  # deprecated warns
    - ifshort
    - golint
    - interfacer
    - deadcode
    - exhaustivestruct
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
