run:
  tests: false
  timeout: 5m
  output:
    format: tab
  skip-dirs:
    - vendor
linters:
  disable-all: true
  enable:
    - bodyclose
    # - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    # - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    # - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - lll
    - misspell
    - nakedret
    # - noctx TODO enable
    # - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - goerr113
    - nestif
    - prealloc
    - testpackage
    - revive
    # - wsl
