version: "3"
services:
  soap:
    image: nikscorp/soap:latest
    build:
      context: .
    container_name: soap
    logging: &default_logging
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
    ports:
      - "127.0.0.1:8202:8080"
    command: "/srv/soap -c  /srv/config/config.yaml"
    volumes:
      - ./config:/srv/config
