version: "3"
services:
  soap:
    image: ghcr.io/nikscorp/soap:latest
    container_name: soap
    logging: &default_logging
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    restart: unless-stopped
    ports:
      - "127.0.0.1:8202:8080"
    networks:
      - monitoring_default
    command: /srv/soap --api-key="${API_KEY}"

networks:
  monitoring_default:
    external: true
