package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i github.com/Nikscorp/soap/internal/pkg/tvmeta.RatingsProvider -o ./ratings_provider_mock.go -n RatingsProviderMock

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RatingsProviderMock implements tvmeta.RatingsProvider
type RatingsProviderMock struct {
	t minimock.Tester

	funcEpisodeRating          func(seriesIMDbID string, season int, episode int) (rating float32, votes uint32, ok bool)
	inspectFuncEpisodeRating   func(seriesIMDbID string, season int, episode int)
	afterEpisodeRatingCounter  uint64
	beforeEpisodeRatingCounter uint64
	EpisodeRatingMock          mRatingsProviderMockEpisodeRating

	funcReady          func() (b1 bool)
	inspectFuncReady   func()
	afterReadyCounter  uint64
	beforeReadyCounter uint64
	ReadyMock          mRatingsProviderMockReady
}

// NewRatingsProviderMock returns a mock for tvmeta.RatingsProvider
func NewRatingsProviderMock(t minimock.Tester) *RatingsProviderMock {
	m := &RatingsProviderMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.EpisodeRatingMock = mRatingsProviderMockEpisodeRating{mock: m}
	m.EpisodeRatingMock.callArgs = []*RatingsProviderMockEpisodeRatingParams{}

	m.ReadyMock = mRatingsProviderMockReady{mock: m}

	return m
}

type mRatingsProviderMockEpisodeRating struct {
	mock               *RatingsProviderMock
	defaultExpectation *RatingsProviderMockEpisodeRatingExpectation
	expectations       []*RatingsProviderMockEpisodeRatingExpectation

	callArgs []*RatingsProviderMockEpisodeRatingParams
	mutex    sync.RWMutex
}

// RatingsProviderMockEpisodeRatingExpectation specifies expectation struct of the RatingsProvider.EpisodeRating
type RatingsProviderMockEpisodeRatingExpectation struct {
	mock    *RatingsProviderMock
	params  *RatingsProviderMockEpisodeRatingParams
	results *RatingsProviderMockEpisodeRatingResults
	Counter uint64
}

// RatingsProviderMockEpisodeRatingParams contains parameters of the RatingsProvider.EpisodeRating
type RatingsProviderMockEpisodeRatingParams struct {
	seriesIMDbID string
	season       int
	episode      int
}

// RatingsProviderMockEpisodeRatingResults contains results of the RatingsProvider.EpisodeRating
type RatingsProviderMockEpisodeRatingResults struct {
	rating float32
	votes  uint32
	ok     bool
}

// Expect sets up expected params for RatingsProvider.EpisodeRating
func (mmEpisodeRating *mRatingsProviderMockEpisodeRating) Expect(seriesIMDbID string, season int, episode int) *mRatingsProviderMockEpisodeRating {
	if mmEpisodeRating.mock.funcEpisodeRating != nil {
		mmEpisodeRating.mock.t.Fatalf("RatingsProviderMock.EpisodeRating mock is already set by Set")
	}

	if mmEpisodeRating.defaultExpectation == nil {
		mmEpisodeRating.defaultExpectation = &RatingsProviderMockEpisodeRatingExpectation{}
	}

	mmEpisodeRating.defaultExpectation.params = &RatingsProviderMockEpisodeRatingParams{seriesIMDbID, season, episode}
	for _, e := range mmEpisodeRating.expectations {
		if minimock.Equal(e.params, mmEpisodeRating.defaultExpectation.params) {
			mmEpisodeRating.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmEpisodeRating.defaultExpectation.params)
		}
	}

	return mmEpisodeRating
}

// Inspect accepts an inspector function that has same arguments as the RatingsProvider.EpisodeRating
func (mmEpisodeRating *mRatingsProviderMockEpisodeRating) Inspect(f func(seriesIMDbID string, season int, episode int)) *mRatingsProviderMockEpisodeRating {
	if mmEpisodeRating.mock.inspectFuncEpisodeRating != nil {
		mmEpisodeRating.mock.t.Fatalf("Inspect function is already set for RatingsProviderMock.EpisodeRating")
	}

	mmEpisodeRating.mock.inspectFuncEpisodeRating = f

	return mmEpisodeRating
}

// Return sets up results that will be returned by RatingsProvider.EpisodeRating
func (mmEpisodeRating *mRatingsProviderMockEpisodeRating) Return(rating float32, votes uint32, ok bool) *RatingsProviderMock {
	if mmEpisodeRating.mock.funcEpisodeRating != nil {
		mmEpisodeRating.mock.t.Fatalf("RatingsProviderMock.EpisodeRating mock is already set by Set")
	}

	if mmEpisodeRating.defaultExpectation == nil {
		mmEpisodeRating.defaultExpectation = &RatingsProviderMockEpisodeRatingExpectation{mock: mmEpisodeRating.mock}
	}
	mmEpisodeRating.defaultExpectation.results = &RatingsProviderMockEpisodeRatingResults{rating, votes, ok}
	return mmEpisodeRating.mock
}

// Set uses given function f to mock the RatingsProvider.EpisodeRating method
func (mmEpisodeRating *mRatingsProviderMockEpisodeRating) Set(f func(seriesIMDbID string, season int, episode int) (rating float32, votes uint32, ok bool)) *RatingsProviderMock {
	if mmEpisodeRating.defaultExpectation != nil {
		mmEpisodeRating.mock.t.Fatalf("Default expectation is already set for the RatingsProvider.EpisodeRating method")
	}

	if len(mmEpisodeRating.expectations) > 0 {
		mmEpisodeRating.mock.t.Fatalf("Some expectations are already set for the RatingsProvider.EpisodeRating method")
	}

	mmEpisodeRating.mock.funcEpisodeRating = f
	return mmEpisodeRating.mock
}

// When sets expectation for the RatingsProvider.EpisodeRating which will trigger the result defined by the following
// Then helper
func (mmEpisodeRating *mRatingsProviderMockEpisodeRating) When(seriesIMDbID string, season int, episode int) *RatingsProviderMockEpisodeRatingExpectation {
	if mmEpisodeRating.mock.funcEpisodeRating != nil {
		mmEpisodeRating.mock.t.Fatalf("RatingsProviderMock.EpisodeRating mock is already set by Set")
	}

	expectation := &RatingsProviderMockEpisodeRatingExpectation{
		mock:   mmEpisodeRating.mock,
		params: &RatingsProviderMockEpisodeRatingParams{seriesIMDbID, season, episode},
	}
	mmEpisodeRating.expectations = append(mmEpisodeRating.expectations, expectation)
	return expectation
}

// Then sets up RatingsProvider.EpisodeRating return parameters for the expectation previously defined by the When method
func (e *RatingsProviderMockEpisodeRatingExpectation) Then(rating float32, votes uint32, ok bool) *RatingsProviderMock {
	e.results = &RatingsProviderMockEpisodeRatingResults{rating, votes, ok}
	return e.mock
}

// EpisodeRating implements tvmeta.RatingsProvider
func (mmEpisodeRating *RatingsProviderMock) EpisodeRating(seriesIMDbID string, season int, episode int) (rating float32, votes uint32, ok bool) {
	mm_atomic.AddUint64(&mmEpisodeRating.beforeEpisodeRatingCounter, 1)
	defer mm_atomic.AddUint64(&mmEpisodeRating.afterEpisodeRatingCounter, 1)

	if mmEpisodeRating.inspectFuncEpisodeRating != nil {
		mmEpisodeRating.inspectFuncEpisodeRating(seriesIMDbID, season, episode)
	}

	mm_params := &RatingsProviderMockEpisodeRatingParams{seriesIMDbID, season, episode}

	// Record call args
	mmEpisodeRating.EpisodeRatingMock.mutex.Lock()
	mmEpisodeRating.EpisodeRatingMock.callArgs = append(mmEpisodeRating.EpisodeRatingMock.callArgs, mm_params)
	mmEpisodeRating.EpisodeRatingMock.mutex.Unlock()

	for _, e := range mmEpisodeRating.EpisodeRatingMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.rating, e.results.votes, e.results.ok
		}
	}

	if mmEpisodeRating.EpisodeRatingMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmEpisodeRating.EpisodeRatingMock.defaultExpectation.Counter, 1)
		mm_want := mmEpisodeRating.EpisodeRatingMock.defaultExpectation.params
		mm_got := RatingsProviderMockEpisodeRatingParams{seriesIMDbID, season, episode}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmEpisodeRating.t.Errorf("RatingsProviderMock.EpisodeRating got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmEpisodeRating.EpisodeRatingMock.defaultExpectation.results
		if mm_results == nil {
			mmEpisodeRating.t.Fatal("No results are set for the RatingsProviderMock.EpisodeRating")
		}
		return (*mm_results).rating, (*mm_results).votes, (*mm_results).ok
	}
	if mmEpisodeRating.funcEpisodeRating != nil {
		return mmEpisodeRating.funcEpisodeRating(seriesIMDbID, season, episode)
	}
	mmEpisodeRating.t.Fatalf("Unexpected call to RatingsProviderMock.EpisodeRating. %v %v %v", seriesIMDbID, season, episode)
	return
}

// EpisodeRatingAfterCounter returns a count of finished RatingsProviderMock.EpisodeRating invocations
func (mmEpisodeRating *RatingsProviderMock) EpisodeRatingAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmEpisodeRating.afterEpisodeRatingCounter)
}

// EpisodeRatingBeforeCounter returns a count of RatingsProviderMock.EpisodeRating invocations
func (mmEpisodeRating *RatingsProviderMock) EpisodeRatingBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmEpisodeRating.beforeEpisodeRatingCounter)
}

// Calls returns a list of arguments used in each call to RatingsProviderMock.EpisodeRating.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmEpisodeRating *mRatingsProviderMockEpisodeRating) Calls() []*RatingsProviderMockEpisodeRatingParams {
	mmEpisodeRating.mutex.RLock()

	argCopy := make([]*RatingsProviderMockEpisodeRatingParams, len(mmEpisodeRating.callArgs))
	copy(argCopy, mmEpisodeRating.callArgs)

	mmEpisodeRating.mutex.RUnlock()

	return argCopy
}

// MinimockEpisodeRatingDone returns true if the count of the EpisodeRating invocations corresponds
// the number of defined expectations
func (m *RatingsProviderMock) MinimockEpisodeRatingDone() bool {
	for _, e := range m.EpisodeRatingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.EpisodeRatingMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterEpisodeRatingCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcEpisodeRating != nil && mm_atomic.LoadUint64(&m.afterEpisodeRatingCounter) < 1 {
		return false
	}
	return true
}

// MinimockEpisodeRatingInspect logs each unmet expectation
func (m *RatingsProviderMock) MinimockEpisodeRatingInspect() {
	for _, e := range m.EpisodeRatingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RatingsProviderMock.EpisodeRating with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.EpisodeRatingMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterEpisodeRatingCounter) < 1 {
		if m.EpisodeRatingMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RatingsProviderMock.EpisodeRating")
		} else {
			m.t.Errorf("Expected call to RatingsProviderMock.EpisodeRating with params: %#v", *m.EpisodeRatingMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcEpisodeRating != nil && mm_atomic.LoadUint64(&m.afterEpisodeRatingCounter) < 1 {
		m.t.Error("Expected call to RatingsProviderMock.EpisodeRating")
	}
}

type mRatingsProviderMockReady struct {
	mock               *RatingsProviderMock
	defaultExpectation *RatingsProviderMockReadyExpectation
	expectations       []*RatingsProviderMockReadyExpectation
}

// RatingsProviderMockReadyExpectation specifies expectation struct of the RatingsProvider.Ready
type RatingsProviderMockReadyExpectation struct {
	mock *RatingsProviderMock

	results *RatingsProviderMockReadyResults
	Counter uint64
}

// RatingsProviderMockReadyResults contains results of the RatingsProvider.Ready
type RatingsProviderMockReadyResults struct {
	b1 bool
}

// Expect sets up expected params for RatingsProvider.Ready
func (mmReady *mRatingsProviderMockReady) Expect() *mRatingsProviderMockReady {
	if mmReady.mock.funcReady != nil {
		mmReady.mock.t.Fatalf("RatingsProviderMock.Ready mock is already set by Set")
	}

	if mmReady.defaultExpectation == nil {
		mmReady.defaultExpectation = &RatingsProviderMockReadyExpectation{}
	}

	return mmReady
}

// Inspect accepts an inspector function that has same arguments as the RatingsProvider.Ready
func (mmReady *mRatingsProviderMockReady) Inspect(f func()) *mRatingsProviderMockReady {
	if mmReady.mock.inspectFuncReady != nil {
		mmReady.mock.t.Fatalf("Inspect function is already set for RatingsProviderMock.Ready")
	}

	mmReady.mock.inspectFuncReady = f

	return mmReady
}

// Return sets up results that will be returned by RatingsProvider.Ready
func (mmReady *mRatingsProviderMockReady) Return(b1 bool) *RatingsProviderMock {
	if mmReady.mock.funcReady != nil {
		mmReady.mock.t.Fatalf("RatingsProviderMock.Ready mock is already set by Set")
	}

	if mmReady.defaultExpectation == nil {
		mmReady.defaultExpectation = &RatingsProviderMockReadyExpectation{mock: mmReady.mock}
	}
	mmReady.defaultExpectation.results = &RatingsProviderMockReadyResults{b1}
	return mmReady.mock
}

// Set uses given function f to mock the RatingsProvider.Ready method
func (mmReady *mRatingsProviderMockReady) Set(f func() (b1 bool)) *RatingsProviderMock {
	if mmReady.defaultExpectation != nil {
		mmReady.mock.t.Fatalf("Default expectation is already set for the RatingsProvider.Ready method")
	}

	if len(mmReady.expectations) > 0 {
		mmReady.mock.t.Fatalf("Some expectations are already set for the RatingsProvider.Ready method")
	}

	mmReady.mock.funcReady = f
	return mmReady.mock
}

// Ready implements tvmeta.RatingsProvider
func (mmReady *RatingsProviderMock) Ready() (b1 bool) {
	mm_atomic.AddUint64(&mmReady.beforeReadyCounter, 1)
	defer mm_atomic.AddUint64(&mmReady.afterReadyCounter, 1)

	if mmReady.inspectFuncReady != nil {
		mmReady.inspectFuncReady()
	}

	if mmReady.ReadyMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmReady.ReadyMock.defaultExpectation.Counter, 1)

		mm_results := mmReady.ReadyMock.defaultExpectation.results
		if mm_results == nil {
			mmReady.t.Fatal("No results are set for the RatingsProviderMock.Ready")
		}
		return (*mm_results).b1
	}
	if mmReady.funcReady != nil {
		return mmReady.funcReady()
	}
	mmReady.t.Fatalf("Unexpected call to RatingsProviderMock.Ready.")
	return
}

// ReadyAfterCounter returns a count of finished RatingsProviderMock.Ready invocations
func (mmReady *RatingsProviderMock) ReadyAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReady.afterReadyCounter)
}

// ReadyBeforeCounter returns a count of RatingsProviderMock.Ready invocations
func (mmReady *RatingsProviderMock) ReadyBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmReady.beforeReadyCounter)
}

// MinimockReadyDone returns true if the count of the Ready invocations corresponds
// the number of defined expectations
func (m *RatingsProviderMock) MinimockReadyDone() bool {
	for _, e := range m.ReadyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ReadyMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterReadyCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReady != nil && mm_atomic.LoadUint64(&m.afterReadyCounter) < 1 {
		return false
	}
	return true
}

// MinimockReadyInspect logs each unmet expectation
func (m *RatingsProviderMock) MinimockReadyInspect() {
	for _, e := range m.ReadyMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to RatingsProviderMock.Ready")
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ReadyMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterReadyCounter) < 1 {
		m.t.Error("Expected call to RatingsProviderMock.Ready")
	}
	// if func was set then invocations count should be greater than zero
	if m.funcReady != nil && mm_atomic.LoadUint64(&m.afterReadyCounter) < 1 {
		m.t.Error("Expected call to RatingsProviderMock.Ready")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RatingsProviderMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockEpisodeRatingInspect()

		m.MinimockReadyInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RatingsProviderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RatingsProviderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockEpisodeRatingDone() &&
		m.MinimockReadyDone()
}
