name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.BOT_PAT }}
      - name: Build the Docker images
        run: docker-compose build
      - name: Launch backend
        env:
          API_KEY: ${{ secrets.OMDB_API_KEY }}
        run: docker-compose up -d
      - name: Run simple test
        run: curl http://127.0.0.1:8202/search/lost
      - name: Run simple test2
        run: curl http://127.0.0.1:8202/id/tt0411008
      - name: Show logs
        run: docker-compose logs
      - name: Stop backend
        run: docker-compose stop
