name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.BOT_PAT }}
      - name: Build the Docker images
        run: docker-compose build
      - name: Launch backend
        env:
          API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: docker-compose up -d
      - name: Run simple test
        run: curl http://127.0.0.1:8202/search/lost
      - name: Run simple test2
        run: curl http://127.0.0.1:8202/id/4607
      - name: Show logs
        run: docker-compose logs
      - name: Stop backend
        run: docker-compose stop
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run Unit tests
      run: |
        go test -race -covermode atomic -coverprofile=covprofile ./...
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@v0.0.11
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GOVERALLS_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github
